config/routes.rb
Rails.application.routes.draw do
  get 'todos/new'
  get 'todos/index'
  get 'todos/show'
  root 'pages#home'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end
  
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:success] = "Todo Created"
      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end

  def show
    
  end

  def edit 
    
  end

  def update 
    if @todo.update(todo_params)
      flash[:success] = "Todo is Updated"
      redirect_to @todo
    else
      render 'edit'
    end
  end

  def destroy
    @todo.destroy
    flash[:danger] = "Todo had been deleted"
    redirect_to todos_path
  end


  private

  def todo_params 
    params.require(:todo).permit(:name, :description)
  end

  def set_todo 
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_flash_class(flash_type)
    case flash_type
    when 'success'
      'alert alert-success'
    when 'danger'
      'alert alert-danger'
    when 'notice'
      'alert alert-info'
    else
      flash_type.to_s
    end    
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_errors.html.erb
<div class="container">
  <% if obj.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h3 class="alert-heading">The Following Errors Prevented the Todo from Being Saved</h3>
        <ul>
          <% @todo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= bootstrap_flash_class(name) %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-md bg-dark justify-content-between">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-nav">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse dual-nav w-100 ">
    <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to ' Home', "#", class: "btn btn btn-outline-* text-white" %>
    </li>
    <li class="nav-item">
      <%= link_to ' Create Todo', new_todo_path, class: "btn btn btn-outline-* text-white" %>
    </li>

    <li class="nav-item">
      <%= link_to 'All Todos', todos_path, class: "btn btn btn-outline-* text-white" %>
    </li>

    <li class="nav-item">
    <div class="dropdown">
    <button type="button" class="btn btn-outline-* dropdown-toggle" data-toggle="dropdown">
      <%#= link_to 'Whats Inside', "#", class: "" %> 
    </button> 
    <div class="dropdown-menu">
      <%#= link_to 'Articles', articles_path, class: "dropdown-item mx-auto" %> 
        <%#= link_to "Categories", categories_path, class: "dropdown-item mx-auto" %>
        <%# if logged_in? && current_user.admin?%>
        <%#= link_to "Create Article", new_article_path, class: "dropdown-item mx-auto" %>
        <%#= link_to "Create a Category", new_category_path, class: "dropdown-item mx-auto"%>
      <%# end %>
    </div>
    </div>
    </li>

    <%# if logged_in? %>
      <li class="nav-item">
        <div class="dropdown">
          <button type="button" class="btn btn-outline-* dropdown-toggle" data-toggle="dropdown">
            <%#= link_to current_user.username %> <%#= "(Admin)" if current_user.admin? %>
          </button>
        <div class="dropdown-menu">
          <%#= link_to "Show User", user_path(current_user), class: "dropdown-item mx-auto" %>
          <%#= link_to "Edit User", edit_user_path(current_user), class: "dropdown-item mx-auto" %>
        </div>
        </div>
      </li>
    <%# end %>

  </ul>
  </div>
  <a href="/" class="navbar-brand mx-auto d-block text-center w-100 logo-name">TODO</a>
  <div class="navbar-collapse collapse dual-nav w-100">
    <ul class="nav navbar-nav ml-auto">
      <%# if logged_in? %>
        <li class="nav-item"> <%#= link_to 'Users', users_path, class: "btn btn btn-outline-* show-button " %></li>
      <%# end %>
      <%# if current_user %> 
        <li><%#= link_to "Log Out", login_path, method: :delete, class: "btn btn-default" %></li>
      <%# else %> <li><%#= link_to "Log in", login_path, class: "btn btn-default" %></li>
      <%# end %> 
    </ul> 
  </div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoInRails6</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= render "layouts/flash"%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1 class="">To Do List using Rails 6...</h1>
</div>


<div class="card mr-1 ml-1">
  <div class="card-body ">
    <h4 class="">Hello and welcome to the To Do app. This is just like a Chores list 
      you create at home where you can add a chore and delete it 
      once its done Give it a try!!</h4>
  </div>
</div>

<div class="container">
  
    <div>
      <p><%#= link_to "Create a Todo", new_todo_path, class: "btn btn-default btn-lg fancy" %></p>
    </div>
  
</div>

app/views/todos/_errors.html.erb
<% if @todo.errors.any? %>
  <h3>The Following Errors Prevented the Todo from Being Saved</h3>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

app/views/todos/_form.html.erb
<div class=" row justify-content-center">
  <div class="col-8">
    <div class="card show-card text-center">
      <%= form_with(model: @todo, local: true)  do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "form-label float-left mt-1" %><br />
          <%= f.text_field :name, class: "form-control form-decoration", 
                                  placeholder: "Add Name Here" %>
        </div>
        <div class="form-group">
          <%= f.label :description, class:"form-label float-left" %><br />
          <%= f.text_area :description, class: "form-control form-decoration", 
                                        placeholder: "Add Description Here" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Todos List", todos_path, class: "btn btn-warning"%>
        </div>
      <% end %>
    </div>
  </div>
</div> 
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
    
 

app/views/todos/_spare.html.erb
<div class="container">
  <div class="col-md-10 offset-md-3">
    <form class="mx-auto">
    <%= form_with(model: @todo, local: true) do |f| %>

      <div class="form-group mt-3">
        <div class="control-label col-md-6">
          <%= f.label :todo_name %> 
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: 'form-control', placeholder: "Name of Todo", autofocus: true %>
        </div>
      </div>  

      <div class="form-group">
        <div class="control-label col-md-6">
          <%= f.label :todo_description %> 
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 5, class: 'form-control', placeholder: "Description of Todo" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary" %> 
          <%= link_to "Todos", todos_path, class: "btn btn-secondary" %>
        </div>
      </div>
    <% end %>
 </form>
  </div>
</div>

app/views/todos/edit.html.erb
<h2 class="text-center">Edit Todo</h2>

<%= render "todos/errors"%>
<%= render "todos/form"%>

app/views/todos/index.html.erb
<div class="container">
  <div class="text-center">
    <h1><%#= current_user.name %>'s to do List</h1>
    </div>
        <p class="text-center">
          <%= link_to "Create a To Do", new_todo_path, class: "btn btn-success" %>
          <%#= link_to "log Out", login_path, method: :delete, class: "btn btn-danger" %>
          <%#= link_to "Users", users_path(@users), class: "btn btn-primary bttn" %>
        </p>
           
        <div class="card ml-5 mr-5">
          
            <% @todos.each do |todo| %>
            <div class="card-index">
              <div class="card-block text-center">
                <div class="card-header">Todo: <%= todo.name %></div>
              </div>
            </div>
            <div class="card-body text-center">
               <p>Description: <%= todo.description %></p>
               <%= link_to "View", todo_path(todo), class: "btn btn-info bttn" %>
                <%# if logged_in? && (current_user == todo.user || current_user.admin?) %>
                  <%= link_to "Edit", edit_todo_path(todo), class: "btn btn-warning bttn" %>
                  <%= link_to "Delete", todo_path(todo), method: :delete, data: {confirm: "Are you sure??"}, 
                                                                      class: "btn btn-danger bttn" %>
                <%# end %>
                </div>
           <% end %>
          
        </div>
           
        
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="card">
  <div class="card-header mx-auto">
    <h2>Create a New Todo</h2>
  </div>
</div> 


<%= render "layouts/errors", obj: @todo %>
<%= render "todos/form" %>

app/views/todos/show.html.erb
<div class="show-panel">
  <div class="card show-card">
  <h1 class="text-center mt-4 object-color"><%= @todo.name %></h1>
    <p class="text-center object-color">Created by:
      <%#= @todo.user.username if @todo.user %>
    </p>
    <p class="text-center mt-4 object-color">Description: <%= @todo.description %></p>
    <p class="text-center">
      <%= link_to "Home Page", root_path, class: "btn btn-primary " %> 
      <%= link_to "All todos", todos_path, class: "btn btn-info " %> 
      <%# if logged_in? && (@todo.user == current_user || current_user.admin?) %>
        <%= link_to "Edit Article", edit_todo_path(@todo), class: "btn btn-warning " %> 
        <%= link_to "Delete Todo", todo_path(@todo), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      <%# end %>
    </p>
  </div>
</div>